### ISSUE TITLE
how can I get the coordinates of the eye-track points in the world view

### ISSUE THREAD

**Issue by Y-pandaman** [pupil-labs/pupil#2178]
Hi, how can I get the coordinates of the eye-track points in the world view, I have these data now:
```
diameter: 19.2537832723
    confidence: 1.0
    model_id: 0
    model_confidence: 1.0
    pupil_timestamp: 19135.7830362
    model_birth_timestamp: 0.0
    diameter_3d: -5830174.17739
    method: ''
    topic: "pupil.1.3d"
    phi: -1.85660011517
    theta: 1.30883943009
    id: 1
    norm_pos: 
      x: 0.325790457729
      y: 0.351124236315
      z: 0.0
    projected_sphere_axes: 
      x: 3.39965073563
      y: 3.39965073563
      z: 0.0
    projected_sphere_angle: 0.0
    projected_sphere_center: 
      x: 64.1765520944
      y: 124.986970598
      z: 0.0
    sphere_radius: 10.3923048454
    sphere_center: 
      x: -71557.6212315
      y: 76767.7553603
      z: -13611822.8305
    ellipse_axes: 
      x: 17.5398531807
      y: 19.2537832723
      z: 0.0
    ellipse_angle: 48.197613583
    ellipse_center: 
      x: 62.551767884
      y: 124.584146628
      z: 0.0
    circle_3d_radius: -2915087.0887
    circle_3d_center: 
      x: -71560.4511677
      y: 76770.4466678
      z: -13611832.4611
    circle_3d_normal: 
      x: -0.272310740343
      y: 0.258971183813
      z: -0.926704260618

```

```
gazes: 
  - 
    confidence: 1.0
    norm_pos: 
      x: 0.994254022255
      y: 1.15792072264
      z: 0.0
    gaze_point_3d: 
      x: 7237892.13836
      y: -9967655.48389
      z: 4740183.02802
    gaze_normal_3d: 
      x: 0.417557034886
      y: -0.907730531952
      z: 0.0408828078602
    pupil_timestamp: 19691.2590325
    eye_center_3d: 
      x: 7237683.35984
      y: -9967201.61863
      z: 4740162.58662

```

**Comment by qalhata** [comment]
Looks interesting!

Admin @ Qalhata Technologies Ltd

Tel: 01167751878
***@***.*** ***@***.***>
www.qalhatatech.com

Address: Colony, 5 Piccadilly Place, Manchester, M1 3BR






_____________________________

Disclaimer: This email and any attachments to it are confidential and may
contain legally privileged information. This e-mail message and its
contents are intended solely for the use of the individual to whom it
is addressed. Any views or opinions expressed are solely those of
the author and do not necessarily represent those of Qalhata Technologies
Limited. If you are not the intended recipient of this email, you must
neither take any action based upon its contents nor copy nor show it to
anyone. Kindly note that e-mail may be susceptible to data corruption,
interception and unauthorised amendment. Qalhata Technologies Limited does
not accept liability for any such corruption, interception or amendment or
the consequences thereof.

Please contact the sender if you believe you have received this email in
error.

**Comment by N-M-T** [comment]
@Y-pandaman  ‘gaze_point_3d' describes gaze coordinates within the world camera coordinate system. For future reference, you can see a description of the data made available in our documentation: https://docs.pupil-labs.com/core/software/pupil-player/#raw-data-exporter

**Comment by Y-pandaman** [comment]
Although I have the camera's internal [reference](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/camera_models.py#L26-L152) and world coordinates, the camera's rotation matrix R and translation matrix T are missing and I still can't get the coordinates of the eye trajectory in the world image

**Comment by N-M-T** [comment]
You can obtain the headset's rotation and translation by using the ['Headpose Tracker' plugin](https://docs.pupil-labs.com/core/software/pupil-player/#head-pose-tracking).
`gaze_point_3d_*`  describes the position of the 3d gaze point (the point the subject looks at) in the world camera coordinate system
`norm_pos_*` describes the position of gaze in the world image frame in normalized coordinates
Important to note: For gaze data to exist, you must [calibrate the eye tracker](https://docs.pupil-labs.com/core/#_4-calibration)

**Comment by Y-pandaman** [comment]
The 'Headpose Tracker' plugin how to output the rotation and translation of the head in real time?

**Comment by papr** [comment]
Maybe, to take a step back, the gaze data also includes the eye model location and rotation in scene camera coordinates. They are used to infer the 3d gaze point. Is this what you were referring to?

Should you be interested in the headset pose in relation to an external coordinate system then the Headpose Tracker would likely be the correct choice. As @N-M-T linked already, you can find more information in our documentation https://docs.pupil-labs.com/core/software/pupil-player/#head-pose-tracking
